# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://wallacekelly.github.io/
gitlocation: https://github.com/WallaceKelly/WallaceKelly.github.io.git
gitbranch: gh-pages
title: Wallace Kelly Blog
description: >
    Wallace Kelly writes about F#, WPF, async, ClickOnce and
    other software development topics.
source: source/
blog: source/blog/
blogIndex: source/blog/index.cshtml
layouts: layouts
content: content
template: tools/empty-template.html
output: output/
deploy: deploy
themes: themes